version: "3.9"
services:
  web:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEFAULT_EXPIRATION: 3600
      RECAPTCHA_SECRET: $RECAPTCHA_SECRET
    ports:
      - "8080:80"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
