version: "3.9"
services:
  web:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: always
    # volumes: #useful for local css
    #   - ../views/:/private-notes/views/
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
